### ISSUE TITLE
Add MIP callbacks support to XPRESS interface

### ISSUE THREAD

**Issue by pet-mit** [rte-france/or-tools#15]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver

**Describe the problem you are trying to solve.**
Use advanced MIP callbacks with XPRESS to intercept B&B steps

**Describe the solution you'd like**
Implement already existing callbacks of solver_interface into xpress_interface

**Additional context**
It seems Gurobi is the only solver that already supports this

**Comment by flomnes** [comment]
It would be nice to clarify the meaning of "advanced MIP callbacks". Here's what I found :
- In function `GurobiInterface::Solve` (part of the interface), a custom branching priority can be set
- Function `GurobiMPCallbackContext::NumExploredNodes` (part of the interface) seems to return the number of explored nodes, using a callback from Gurobi
- Class `MPCallbackContext` isn't overriden for XPRESS, although it seems to expose interesting functions such as `AddCut`, `AddLazyConstraint`, `SuggestSolution`, etc.

**Comment by pet-mit** [comment]
A first great example of a callback for me would be each time XPRESS finds a better integer-feasible solution.
For example, we could save the new solution every time it is improved - by x% let's say- ( after re-modelling it into its business form), and come check regularly for the latest solution.
Then we would have an up-to-date best solution without interrupting the solver from searching further.

**Comment by pet-mit** [comment]
For example, "kMipSolution" (see here: https://github.com/rte-france/or-tools/blob/main/ortools/linear_solver/linear_solver_callback.h) is already implemented for Gurobi. It allows to notify an event every time the solver finds a new MIP solution.

**Comment by pet-mit** [comment]
ongoing
