### ISSUE TITLE
XPRESS interface: SetSolverSpecificParameters can only be called once

### ISSUE THREAD

**Issue by pet-mit** [rte-france/or-tools#28]
**What version of OR-Tools and what language are you using?**
Version: v9.2 RTE1.1
Language:  Python 

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
XPRESS

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
Called solver.SetSpecificSolverParameters multiple times with different control parameters:
solver.SetSolverSpecificParameters("param1 value1 param2 value2")
solver.SetSolverSpecificParameters("param3 value3 param4 value4 param5 value5")

**What did you expect to see**
All 5 parameters should have been set, that is actually what is logged by OR-Tools

**What did you see instead?**
In the XPRESS logs, only parameters of last call (ie params 3, 4 & 5) seem to have been set

**Comment by flomnes** [comment]
@pet-mit I could reproduce the bug. I confirm that by default, `Reset` is called at `Solve`. More precisely, this is what happens currently

1. Some parameters are set using `SetSolverSpecificParametersAsString`
2. In `Solve`, `Reset` is called, erasing the model and its parameters
3. `SetSolverSpecificParametersAsString` is called on the new model, but **only with the last parameter provided**

I confirm that #46 fixes this issue.

**Comment by pet-mit** [comment]
After somme digging, I saw that the default implementation in linear_solver.cc is the following: 
~~~cpp
bool MPSolver::SetSolverSpecificParametersAsString(
    const std::string& parameters) {
  solver_specific_parameter_string_ = parameters;
  return interface_->SetSolverSpecificParametersAsString(parameters);
}
~~~

I guess that the "default" expected behaviour is to clear out the old parameters on every new call.
So this is not really a bug, I'm okay with working around it.

I'm closing the issue.
