### ISSUE TITLE
Allow XPRESS to be loaded at runtime

### ISSUE THREAD

**Issue by flomnes** [rte-france/or-tools#33]
Then we wouldn't have to ship multiple .so/.dll

Use `dlopen` on Linux, `LoadLibrary` on Windows.

**Comment by flomnes** [comment]
Here is how Google does it with Gurobi :

1. Define many `extern std::function<...>` in a header file, each corresponding to an XPRS function (see **or-tools/ortools/gurobi/environment.h**)
2. Replace the xpress header file with this one
3. Look for Gurobi in the environment. If found, go to next step. If not, don't add it to the list of available solvers, don't issue an error.
4. Try to load those functions from a dynamic lib at init time
5. Unload these functions at destruction / when the program exits.

They may on

**Comment by pet-mit** [comment]
Can this issue be closed?
