### ISSUE TITLE
libssh dependancy

### ISSUE THREAD

**Issue by klorel** [rte-france/or-tools#43]
On ubuntu, it seems that we need to use the use libssh.so file rather than the one distributed by XPRESS.

**Comment by flomnes** [comment]
Yes, the libssh.so file shipped with XPRESS has an incompatible ABI with the system libssh. I've had issues using git + XPRESS's provided libssh.so (by accident).

Ask FICO not to include libssh.so by default ? **libxprs.so** isn't linked against **libssh.so**, so it shouldn't be needed anyway.
