### ISSUE TITLE
Lazy XPRESS doesn't work in Windows

### ISSUE THREAD

**Issue by flomnes** [rte-france/or-tools#71]
**What version of OR-Tools and what language are you using?**
Version: v9.2-rte2.0.
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
XPRESS + linear_solver

**What operating system (Linux, Windows, ...) and version?**
Windows 11

**What did you do?**
1. Build Antares_Simulator with v9.2-rte2.0
2. Launch `antares-solver --list-solvers`

**What did you expect to see**
```
sirius
coin
xpress
```

**What did you see instead?**
```
sirius
coin
```
+ an error message (see below)
Make sure you include information that can help us debug (full error message, model Proto).

![image](https://user-images.githubusercontent.com/26088210/207319910-b818c292-e7fd-48dd-94a5-dab9b382fa88.png)

**Anything else we should know about your project / environment**
All DLLs were present in C:\xpressmp\bin. A valid licence was present as well.

**Comment by payetvin** [comment]
I tried in my windows VM with the following commands.

$Env:XPRESSDIR = C:\Users\payetvin\xpress-mp-temp
.\antares-8.4-solver.exe

The path of the xprs.dll is valid
![image](https://user-images.githubusercontent.com/113102157/207387174-6d2aad2f-8896-423f-927e-cd5020c2fa56.png)

Result
![image](https://user-images.githubusercontent.com/113102157/207387335-b6b1d546-c321-4312-9540-cfdd6784ed68.png)

**Comment by flomnes** [comment]
I've encountered a similar problem in Linux + XPRESS 8.8.0. Where LD_LIBRARY_PATH didn't point to XPRESSDIR/lib, so libxprs.so's dependencies couldn't be resolved.

**Comment by pet-mit** [comment]
Is this still an issue?

**Comment by flomnes** [comment]
I think you made a contribution to only load the necessary functions. Therefore lazy XPRESS should work with XPRESS 8.8.0 or 8.13.0 ? Although officially, we only support version 9.0

**Comment by pet-mit** [comment]
yes indeed, it should work with any version that has the necessary functions
