### ISSUE TITLE
add XPAUTH_PATH as env variable (not only XPRESS)

### ISSUE THREAD

**Issue by sgatto** [rte-france/or-tools#78]
**What language and solver does this apply to?**
All, 

**Describe the problem you are trying to solve.**
Xpress standard installation defines 2 main env variable (today):
 - `XPAUTH_PATH` path to license
 - `XPRESSDIR` path to xpress root

**Describe the solution you'd like**
today ORtools looks for the variable `XPRESS` (path to license) that the user must define independently , since it's not defined by the Xpress installation
I propose to look for the licence also using `XPAUTH_PATH` environment variable, not only using the `XPRESS` variable.

**Describe alternatives you've considered**
Dropping `XPRESS` and use `XPAUTH_PATH` instead. It could be dangerous for backward compatibility?

**Comment by flomnes** [comment]
Fall back to `XPRESS` if licence isn't found/is invalid in `XPAUTH_PATH`, or if `XPAUTH_PATH` is empty/invalid.

Is `XPAUTH_PATH` defined when XPRESS is installed ?

**Comment by sgatto** [comment]
Yes, the standard Xpress installation defines `XPAUTH_PATH` in the  `bin/xpvars.sh` script that the user can execute or add to `.bashrc`

**Comment by sgatto** [comment]
I don't know why we have this line
https://github.com/rte-france/or-tools/blob/8564311256a299cbb9b8198d0b72af06d50d4c5f/ortools/xpress/environment.cc#L281
We could simply use 
`code = XPRSinit(xpresspath.c_str());`
if no `XPRESS` variable is set and let the user have defined the correct XPAUTH_PATH (I guess this is where the function looks for the licence)
