### ISSUE TITLE
XPRESS logs : Should not be visible unless mpSolver.enableOutput() is called

### ISSUE THREAD

**Issue by MartinBelthle** [rte-france/or-tools#84]
**What version of OR-Tools and what language are you using?**
OR-Tools version: v9.5
XPRESS version: v9.0
Language: Java

**What did you expect to see**

When I'm not calling mpSolver.enableOutput(), I wish there were no Xpress logs. 

**What did you see instead?**

![logs_xpress](https://user-images.githubusercontent.com/102529366/231997123-050b662d-6470-4343-9d83-c26a08c099dd.png)

**Comment by pet-mit** [comment]
https://github.com/rte-france/or-tools/pull/86
